### PR TITLE
Add onArrowClick event support

### PR DESCRIPTION
**Pull request by mavr1k**
use onArrowClick props to use arrow

### CODE REVIEW

**Comment by jochienabuurs** [comment]
This would be nice if implemented

**Comment by narsters** [comment]
I also agree this would be very nice to have.  I would be nice to be able to click on the header and not have the node toggle, only toggle when the arrow is clicked.

**Comment by AlexandraVoda19** [comment]
Has anyone managed to merge this PR in master? It would be really useful! 
Thank you!

**Comment by mavr1k** [comment]
@AlexandraVoda19 Hi. I don't know

**Comment by mavr1k** [comment]
@AlexandraVoda19 Hi! I don't know how to do that, so it will be cool if somebody explain or do it.
Thanks!

**Comment by AlexandraVoda19** [comment]
@mavr1k Since you are only the PR author, you are not able to do the merge by yourself. We need the help from a project contributor.

**Comment by milesrichardson** [comment]
@AlexandraVoda19 I merged this into my fork at https://github.com/milesforks/react-treebeard if you want to use it. Just put this in your package.json:

` "react-treebeard": "https://github.com/milesforks/react-treebeard#c3f31a5421c6e47ed4004ab3f20923e34fb8d022"`

**Comment by AlexandraVoda19** [comment]
@milesrichardson Thank you a lot for your response!
Are you planning on developing this library? Do you need any help?

**Comment by mavr1k** [comment]
@milesrichardson good job!

**Comment by milesrichardson** [comment]
@AlexandraVoda19 It's working for what I need, so no probably not doing much else on it.

**Comment by AlexandraVoda19** [comment]
@milesrichardson Allright! Thank you for sharing your repo! :)

**Pull request closed without merging**
